### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'useReducer')

### ISSUE THREAD

**Issue by EthanBurkett** [awran5/react-simple-typewriter#9] opened 2022-10-04 18:08 UTC
Just got this error when trying to use the function

Code used:
```ts
const [text, count] = useTypewriter({
    words: ["Hi, my name's Ethan", "Developer", "Creator"],
    loop: true,
    delaySpeed: 2000,
  });
  return (
    <div>
      <p>{text}</p>
    </div>
  );
```

**Comment by Gabe-Alvess** [comment] 2022-10-04 19:08
Same problem here! 😞

Code:

 ```ts
import React from "react";
import { useTypewriter, Cursor } from "react-simple-typewriter";

type Props = {};

export default function Profile({}: Props) {
  const [text] = useTypewriter({
    words: ["Developer", "Designer", "Creator"],
    loop: true,
    delaySpeed: 2000,
  });

  return (
    <div>
      <h1>
        <span>{text}</span>
        <Cursor cursorColor="red" />
      </h1>
    </div>
  );
}
```

**Comment by EthanBurkett** [comment] 2022-10-04 19:10
Sometimes the typewriter will work but then randomly it will throw the error and i have to disable it until I feel like trying again and then boom, it magically works again\

**Comment by Dekita** [comment] 2022-10-05 01:17
Same issue here, worked completely fine until now. 

Edit: I set the version in my package.json to `4.0.2` instead of `^4.0.2` (which installed the latest `4.0.3`). The issue is 'resolved'. Not sure what broke it for the current version.

**Comment by awran5** [comment] 2022-10-05 06:13
Hi guys, fixed with [v4.0.5](https://github.com/awran5/react-simple-typewriter/compare/v4.0.4...v4.0.5) Please test and let me know.

**Comment by Gabe-Alvess** [comment] 2022-10-05 07:13
> Hi guys, fixed with [v4.0.5](https://github.com/awran5/react-simple-typewriter/compare/v4.0.4...v4.0.5) Please test and let me know.

Working just fine for me 😁 
Thank You 👍

**Comment by jessicaan** [comment] 2022-10-05 12:49
> Hi guys, fixed with [v4.0.5](https://github.com/awran5/react-simple-typewriter/compare/v4.0.4...v4.0.5) Please test and let me know.

Working!! Thanks!

**Closed as completed** 2022-10-08 02:54 UTC
